# Alicia Enhanced Voice Assistant Configuration
# This configuration file defines settings for the local voice assistant

assistant:
  name: "Alicia"
  version: "2.0.0"
  language: "en"
  wake_word: "alicia"

# Wyoming Protocol Services
wyoming:
  whisper:
    url: "tcp://wyoming-whisper:10300"
    model: "medium"
    language: "en"
  piper:
    url: "tcp://wyoming-piper:10200"
    voice: "en_US-lessac-medium"
    quality: "medium"

# MQTT Configuration
mqtt:
  broker: "mosquitto"
  port: 1883
  username: "voice_assistant"
  password: "alicia_ha_mqtt_2024"
  topics:
    command: "alicia/voice/command"
    response: "alicia/voice/response"
    status: "alicia/voice/status"
    wake: "alicia/voice/wake"

# LLM Integration (for future use)
llm:
  enabled: false
  endpoint: ""
  model: ""
  temperature: 0.7
  max_tokens: 150

# Voice Processing Settings
voice:
  sample_rate: 16000
  channels: 1
  format: "wav"
  max_audio_length: 30  # seconds

# Device Control
devices:
  lights:
    - "living_room_light"
    - "kitchen_light"
    - "bedroom_light"
  sensors:
    - "temperature_sensor"
    - "motion_sensor"

# Conversation Settings
conversation:
  max_history: 50
  session_timeout: 300  # seconds
  response_timeout: 10   # seconds

# Logging
logging:
  level: "INFO"
  file: "logs/assistant.log"
  max_size: "10MB"
  backup_count: 5

# Security
security:
  enable_encryption: false
  allowed_ips: []
  rate_limit: 10  # requests per minute
