services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    env_file:
      - .env
    environment:
      - TZ=${TIMEZONE:-UTC}
    volumes:
      - ./config:/config
      - ./logs:/config/logs
      - /etc/localtime:/etc/localtime:ro
      - ./setup-mqtt.sh:/setup-mqtt.sh
    ports:
      - "18123:8123"
    restart: unless-stopped
    depends_on:
      - mqtt
    networks:
      - alicia_network
    command: ["/bin/bash", "-c", "python -m homeassistant --config /config & sleep 30 && /setup-mqtt.sh && wait"]
    healthcheck:
      test: ["CMD", "curl", "-f", "-H", "Authorization: Bearer ${HA_API_PASSWORD}", "http://localhost:8123/api/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  mqtt:
    container_name: alicia_mqtt
    image: eclipse-mosquitto:2.0
    volumes:
      - ../mqtt/config:/mosquitto/config
      - ../mqtt/data:/mosquitto/data
      - ../mqtt/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: unless-stopped
    networks:
      - alicia_network
    healthcheck:
      test: ["CMD-SHELL", "mosquitto_sub -t '$$SYS/#' -C 1 -h localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  alicia_network:
    driver: bridge
    name: alicia_network
    external: true
