version: '3.8'

services:
  # Backend service
  alicia-config-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
    environment:
      - NODE_ENV=development
      - MQTT_BROKER=alicia_bus_core
      - MQTT_PORT=1883
      - MQTT_USERNAME=config_manager
      - MQTT_PASSWORD=alicia_config_2024
      - CONFIG_PATH=/app/config
      - FRONTEND_URL=http://localhost:3002
    depends_on:
      - alicia_bus_core
    networks:
      - alicia_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend service
  alicia-config-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3000
      - VITE_SOCKET_URL=http://localhost:3000
    depends_on:
      - alicia-config-backend
    networks:
      - alicia_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MQTT Broker (for local development)
  alicia_bus_core:
    image: eclipse-mosquitto:2.0.18
    ports:
      - "1883:1883"
      - "8883:8883"
      - "9001:9001"
    volumes:
      - ./bus-config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./bus-config/passwords:/mosquitto/config/passwords:ro
      - ./bus-config/acl:/mosquitto/config/acl:ro
      - ./bus-data:/mosquitto/data
      - ./bus-logs:/mosquitto/log
    environment:
      - MQTT_BROKER_NAME=alicia-bus-core
    networks:
      - alicia_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mosquitto_pub", "-h", "localhost", "-t", "alicia/system/health/broker", "-m", "healthy", "-u", "admin", "-P", "alicia_admin_2024"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  alicia_network:
    driver: bridge
    name: alicia_network
