# Home Assistant Configuration for Alicia Project
# This configuration connects HA to PostgreSQL and sets up basic integrations

# Basic Home Assistant Configuration
homeassistant:
  name: Alicia Home Assistant
  latitude: !env_var HA_LATITUDE
  longitude: !env_var HA_LONGITUDE
  elevation: !env_var HA_ELEVATION
  unit_system: !env_var HA_UNIT_SYSTEM
  time_zone: !env_var HA_TIME_ZONE
  external_url: "http://localhost:8123"

# HTTP Configuration
http:
  server_host: 0.0.0.0
  server_port: 8123
  use_x_forwarded_for: true
  trusted_proxies: []
  ip_ban_enabled: false
  login_attempts_threshold: 0

# Database Configuration (PostgreSQL)
recorder:
  db_url: !env_var POSTGRES_DB_URL
  purge_keep_days: 365
  commit_interval: 1

# History Configuration
history:
  exclude:
    domains:
      - automation
      - script
      - updater

# Logbook Configuration
logbook:
  exclude:
    domains:
      - automation
      - script
      - updater

# Frontend Configuration
frontend:
  themes: !include_dir_merge_named themes/

# API Configuration
api:

# Media Source (required for TTS)
media_source:

# System Health
system_health:

# Sonos Integration
sonos:
  media_player:
    hosts:
      - 192.168.1.101
      - 192.168.1.102
      - 192.168.1.103

# Text-to-Speech Integration
tts:
  - platform: google_translate
    language: 'en'
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300

# Zeroconf and SSDP for device discovery
zeroconf:
ssdp:



# Logger Configuration
logger:
  default: info
  logs:
    homeassistant.components.recorder: warning
    homeassistant.components.http: warning
    sqlalchemy: warning
    homeassistant.components.sonos: warning
    homeassistant.components.mqtt: debug

# Automation and Script Storage
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# MQTT Entities will be auto-discovered via MQTT discovery
# No manual entity definitions needed - devices will register themselves
# Example discovery topics that devices can publish to:
# - homeassistant/sensor/livingroom_temperature/config
# - homeassistant/switch/bedroom_light/config

# Include additional configuration files
group: !include groups.yaml
binary_sensor: !include binary_sensors.yaml
